// <auto-generated />
namespace QA_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class adding_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_field));
        
        string IMigrationMetadata.Id
        {
            get { return "201911152254473_adding_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
